name: Mise à jour des marées

on:
  workflow_dispatch:

  schedule:
    - cron: "5 * * * *"

permissions:
  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Générer tides.json
        run: node scripts/update_tides.js

      - name: Commit des modifications
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/tides.json

          git diff --cached --quiet || git commit -m "Mise à jour automatique des marées"

          git push
